### PR TITLE
fix: add better error messages for parsing datasource urls

### LINKED ISSUE #1897: Bad error message when selecting from non-existent file
## Description

```
> select * from './testdata/userdata1.parquet';
Error: External error: Unable to convert path "./testdata/userdata1.parquet" to URL
```

The error is confusing, and doesn't indicate that the file was not found. Tested on 0.5.1 and latest main.

The correct path is `./testdata/parquet/userdata1.parquet`, which works as expected.

### PR DESCRIPTION
**Pull request by universalmind303**
closes #1897
closes https://github.com/GlareDB/glaredb/issues/1936

The error messages should properly bubble up now. 

Additionally, we now canonicalize the relative paths during `DatasourceUrl::try_new`. This ensures that the path is absolute, and that it is a valid file/directory.

### CODE REVIEW

File: crates/datasources/src/object_store/local.rs [hunk 1]
```diff
@@ -49,13 +50,13 @@ impl ObjStoreAccess for LocalStoreAccess {
...
         )?;
-
         let mut objects = Vec::new();
         for path in paths {
             let path = path?;
             let meta = path.metadata()?;
+            let loc = self.path(path.to_string_lossy().as_ref());
             let meta = ObjectMeta {
-                location: self.path(path.to_string_lossy().as_ref())?,
+                location: loc?,
```
Comment (universalmind303) [inline crates/datasources/src/object_store/local.rs:59]: revert.

Comment (tychoish) [inline crates/datasources/src/object_store/local.rs:59]:
```suggestion
                location: self.path(path.to_string_lossy().as_ref())?,
```
push the button ;)

**Review by tychoish — APPROVED** [review]
looks good, modulo the test failure
