### PR TITLE
fix: builtin table functions should not need a schema to resolve

### LINKED ISSUE #1383: Table functions shouldn't need schema?
## Context

```
〉create schema test_schema;
create schema

〉set search_path to test_schema;
set local

〉show search_path;
+-------------+
| search_path |
+-------------+
| test_schema |
+-------------+

〉create view test_view as select * from generate_series(1, 3);
Error: Error during planning: Missing table function: 'generate_series'

〉create view test_view as select * from public.generate_series(1, 3);
create view
```

## Expected

Successful query.

## Actual

Error (since schema not specified).

### PR DESCRIPTION
**Pull request by adhish20**
Fixes #1383

### CODE REVIEW

**Comment by universalmind303** [comment]
can we add some slt's for this?

File: crates/sqlexec/src/metastore/catalog.rs [hunk 1]
```diff
@@ -255,6 +255,30 @@ impl SessionCatalog {
...
+            .expect("object name points to invalid function");
+
+        match ent {
+            CatalogEntry::Function(function) => {
+                if function.meta.builtin && function.func_type == FunctionType::TableReturning {
+                    Some(function.clone())
+                } else {
+                    None
+                }
+            }
```
Comment (vrongmeal) [inline crates/sqlexec/src/metastore/catalog.rs:277]:
```suggestion
            CatalogEntry::Function(function) if function.meta.builtin && function.func_type == FunctionType::TableReturning => {
                Some(function.clone())
            }
```

Can simplify here.

**Review by vrongmeal — COMMENTED** [review]
Generally, it looks good, but we do need some SLTs to go with here.
