### PR TITLE
fix: number of deleted rows returned when there is no where clause

### LINKED ISSUE #1537: Delete not returning correct number of rows deleted
## Description

```
> create table a (a int);
┌┐
└┘
> insert into a values (1);
Write success
> delete from a;
Deleted 0 rows
> select * from a;
┌┐
└┘
```

### PR DESCRIPTION
**Pull request by adhish20**
Fixes #1537

### CODE REVIEW

File: crates/datasources/src/native/access.rs [hunk 1]
```diff
@@ -172,21 +172,32 @@ impl NativeTableStorage {
...
+            let deleted_rows = DeleteBuilder::new(table.delta.object_store(), table.delta.state)
                 .with_predicate(where_expr)
+                .await?
+                .1
+                .num_deleted_rows;
+            if let Some(rows) = deleted_rows {
+                Ok(rows)
+            } else {
+                Ok(0_usize)
+            }
```
Comment (scsmithr) [inline crates/datasources/src/native/access.rs:189]:
```suggestion
            Ok(deleted_rows.unwrap_or_default())
```

**Review by scsmithr — APPROVED** [review]

**Comment by greyscaled** [comment]
@adhish20 && @scsmithr is this something we should add a test for ?

**Comment by adhish20** [comment]
> @adhish20 && @scsmithr is this something we should add a test for ?

It's difficult to add a test for this currently as we do not have a way to assert the return from a sql command
