### PR TITLE
fix: Pushdown SQL Server `WHERE` clause

### LINKED ISSUE #2094: feat: SQL Server followup items
## Description

Initial support added in https://github.com/GlareDB/glaredb/issues/2093. This lays out some follow-up items.

- [x] `read_sqlserver` function: #2310
- [x] Push down expression filters (WHERE): #2316
- [x] `datatype` table SLT tests: #2317 
- [x] Virtual schema thing (for listing tables, column info): #2311

### PR DESCRIPTION
**Pull request by vrongmeal**
Fixes #2094

### CODE REVIEW

File: crates/datasources/src/sqlserver/mod.rs [hunk 1]
```diff
@@ -341,6 +350,76 @@ impl TableProvider for SqlServerTableProvider {
...
+                return Ok(false);
+            }
+        }
+        Expr::IsFalse(expr) => {
+            if write_expr(expr, buf)? {
+                write!(buf, " IS FALSE")?;
+            } else {
+                return Ok(false);
+            }
+        }
```
Comment (scsmithr) [inline crates/datasources/src/sqlserver/mod.rs:404]: Could we add an SLT with a query that would trigger this? SQL Server doesn't have a bool data type, so I'm not positive this would work.

File: crates/datasources/src/sqlserver/mod.rs [hunk 2]
```diff
@@ -341,6 +350,76 @@ impl TableProvider for SqlServerTableProvider {
...
+            ss.push(buf);
+            buf = String::new();
+        }
+    }
+
+    Ok(ss.join(" AND "))
+}
+
+/// Try to write the expression to the string, returning true if it was written.
+fn write_expr(expr: &Expr, buf: &mut String) -> Result<bool> {
```
Comment (universalmind303) [inline crates/datasources/src/sqlserver/mod.rs:369]:
```suggestion
fn try_write_expr(expr: &Expr, buf: &mut String) -> Result<bool> {
```

File: crates/datasources/src/sqlserver/mod.rs (hunk 1 above)
Comment (vrongmeal) [reply crates/datasources/src/sqlserver/mod.rs:404]: Yeah, I just raised a PR to run tests in CI (some issue with local). I will keep resolving stuff accordingly. There are tests in `basic.slti` that will validate this.

File: crates/datasources/src/sqlserver/mod.rs (hunk 2 above)
Comment (vrongmeal) [reply crates/datasources/src/sqlserver/mod.rs:369]: Will rename!

**Review by scsmithr — APPROVED** [review]
